# app-compose.yaml
version: "3.8"

services:
  backend:
    build: ./server
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    expose:
      - "5000"
    networks:
      - app_net
      - redis_net
    restart: unless-stopped

  frontend:
    build: 
      context: ./client
      args:
          - REACT_APP_SOCKET_URL=http://localhost:5000
    ports:
      - "3000:80"
    networks:
      - app_net
    restart: unless-stopped

networks:
  app_net:
    driver: bridge
  redis_net:
    external: true
