name: PROD deployment on astra

on:
  push:
    branches: 
      - main

jobs:
    deploy-prod:
        runs-on: [self-hosted, duodeck]
        steps:

            - uses: actions/checkout@v3

            - name: Bring Down existing containers
              run: docker-compose down

            - name: Start containers
              run: docker-compose up --build -d